### ISSUE TITLE
Labeler 요구사항

### ISSUE THREAD

**Issue by goodgodgd** [jh79783/labeling#7]
### category 선택
- [x] 0~9: 숫자키를 이용해 두 단계로 카테고리 선택
- [x] 차, 사람 같이 빈도가 높은건 최상위 1, 2번으로 바로 선택 가능하게
- [x] 카테고리를 먼저 선택 후 박스를 치도록 설계
- [x] 카테고리는 한번 선택하면 같은 종류의 여러 박스를 연속적으로 그릴수 있음

### 박스 조정
- [x] W, A, S, D: 박스 위치 상하좌우 조절
- [x] R, T, F, G: 박스 너비 높이 증가 축소

### 리스트 삭제
- [x] delete: 객체 리스트에서 삭제

## 파일 입출력
- [x] 기존에 있던 label 파일 불러와서 사진에 박스 그리고 객체 목록에 추가하기
- [x] 객체 목록 추가 삭제 후 저장하기
- [x] 'Next' 버튼 눌러 다음 프레임으로 지나갈때 자동 저장하기
- [x] 일단 거리 값은 '0'으로 채워두기

**Comment by jh79783** [comment]
## 단축키 활용
### category 선택
- ~~0~9: 숫자키를 이용해 두 단계로 카테고리 선택~~
- ~~차, 사람 같이 빈도가 높은건 최상위 1, 2번으로 바로 선택 가능하게~~
- 카테고리를 먼저 선택 후 박스를 치도록 설계 -> 그냥 박스치면 프로그램이 죽음
- ~~카테고리는 한번 선택하면 같은 종류의 여러 박스를 연속적으로 그릴수 있음~~
### 박스 조정
- W, A, S, D: 박스 위치 상하좌우 조절
- R, T, F, G: 박스 너비 높이 증가 축소
### 리스트 삭제
- delete: 객체 리스트에서 삭제
### 파일 입출력
- 기존에 있던 label 파일 불러와서 사진에 박스 그리고 객체 목록에 추가하기
- 객체 목록 추가 삭제 후 저장하기
- 'Next' 버튼 눌러 다음 프레임으로 지나갈때 자동 저장하기 -> save action 버튼 만듬
- 일단 거리 값은 '0'으로 채워두기

**Comment by jh79783** [comment]
## 단축키 활용
### category 선택
- ~~0~9: 숫자키를 이용해 두 단계로 카테고리 선택~~
- ~~차, 사람 같이 빈도가 높은건 최상위 1, 2번으로 바로 선택 가능하게~~
- 카테고리를 먼저 선택 후 박스를 치도록 설계 -> 그냥 박스치면 프로그램이 죽음
- ~~카테고리는 한번 선택하면 같은 종류의 여러 박스를 연속적으로 그릴수 있음~~
### 박스 조정
- W, A, S, D: 박스 위치 상하좌우 조절
- R, T, F, G: 박스 너비 높이 증가 축소
### 리스트 삭제
- ~~delete: 객체 리스트에서 삭제~~
### 파일 입출력
- 기존에 있던 label 파일 불러와서 사진에 박스 그리고 객체 목록에 추가하기 -> 교수님과 의논 필요
- 객체 목록 추가 삭제 후 저장하기
- ~~'Next' 버튼 눌러 다음 프레임으로 지나갈때 자동 저장하기 -> save action 버튼 만듬~~
- 일단 거리 값은 '0'으로 채워두기

**Comment by jh79783** [comment]
- [ ] config.py -> root로

- [ ] pedestrian -> person

- [ ] car -> top으로

- [ ] CategoryTree -> 다른 파일로 분리

- [ ] ObjectListWidget(ListWidget) 클래스 만들기

  - [ ] 리스트위젯 단축키 처리

  - [ ] box_list: 데이터를 list로 갖고있기

  - [ ] def push_back(box) -> box_list에 추가

  - [ ] def pop(index) -> box_list에서 제거

  - [ ] def render() -> self.box_list 변경시 다시 리스트위젯 채우기

    ```
    def event_handle(key):
    	if key == "del":
    		index = self.currentIndex()
    		self.pop(index)
    
    def pop(index)
    	# delete
    	self.render()
    
    def push_back(box)
    	# add
    	self.render()
    ```

- [ ] FileIO 클래스로 파일 입출력 분리

- [ ] 파일 형식은 category(str), x1, y1, x2, y2, distance

- [ ] 기존 형식 변경하는 스크립트 작성

- [ ] 카테고리 2레벨을 '/'로 구분
